version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    open-pull-requests-limit: 5
    target-branch: develop
    schedule:
      interval: "daily"
    commit-message:
      prefix: "#6 - "
