version: "3.7"

services:
  php:
    container_name: hyperdrive-php
    image: php:7.4.0-fpm-alpine
    volumes:
      - .:/application

  composer:
    container_name: hyperdrive-composer
    image: composer:1.9.1
    volumes:
      - .:/application
